# Generated by Django 4.2.4 on 2023-08-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rantal_Station',
            new_name='Rental_Station',
        ),
    ]
