# Generated by Django 4.2.4 on 2023-08-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sci', 'scientific'), ('na', 'nature')], default=None, max_length=3),
        ),
    ]
